name: Itch.io Deploy

on:
  push:

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Windows Build
        run: |
          mkdir -v -p dist/windows
          godot --headless -v --export-debug Windows dist/windows/overculted.exe || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/windows
          stat dist/windows/overculted.exe
      - name: Deploy windows to itch.io
        run: BUTLER_API_KEY=${{ secrets.BUTLER_API_KEY }} butler push dist/windows moonstorm-clerics/overculted-prototype:windows


  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Linux Build
        run: |
          mkdir -v -p dist/linux
          godot --headless -v --export-debug Linux dist/linux/overculted.x86_64 || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/linux
          stat dist/linux/overculted.x86_64
      - name: Deploy linux to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/linux moonstorm-clerics/overculted-prototype:linux

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Web Build
        run: |
          mkdir -v -p dist/web
          godot --headless -v --export-debug Web dist/web/index.html || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/web
          stat dist/web/index.html
      - name: Deploy web build to itch.io (overculted)
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/web moonstorm-clerics/overculted-prototype:html5

  # export-mac:
  #   name: Mac Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.2.2
  #   environment: Godot Dev Env
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #     - name: Issue 120
  #       run: |
  #         mkdir -p /github/home/.config/godot
  #         cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
  #     - name: Sanity check
  #       run: ls /root/.local/share/godot/export_templates
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates
  #         mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
  #     - name: Initial Godot import
  #       shell: bash
  #       run: |
  #         godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
  #         godot --editor --headless --quit || exit 0
  #     - name: Mac Build
  #       run: |
  #         mkdir -v -p dist/macos
  #         godot --headless -v --export-debug macos dist/macos/overculted.dmg || exit 0
  #     - name: Sanity check
  #       run: |
  #         ls -alh dist/
  #         ls -alh dist/macos
  #         stat dist/macos/overculted.dmg
  #     - name: Deploy mac build to itch.io
  #       run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/macos moonstorm-clerics/overculted-prototype:macos
