name: Itch.io Deploy

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]
    branches: [edge, prod]

jobs:
  export-windows:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Windows Build
        run: |
          mkdir -v -p dist/overculted-windows
          godot --headless -v --export-debug overculted-windows dist/overculted-windows/overculted.exe || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/overculted-windows
          stat dist/overculted-windows/overculted.exe
      - name: Deploy windows to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/overculted-windows russmatney/overculted:windows


  export-linux:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Linux Build
        run: |
          mkdir -v -p dist/overculted-linux
          godot --headless -v --export-debug overculted-linux dist/overculted-linux/overculted.x86_64 || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/overculted-linux
          stat dist/overculted-linux/overculted.x86_64
      - name: Deploy linux to itch.io
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/overculted-linux russmatney/overculted:linux

  export-web:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    environment: Godot Dev Env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Issue 120
        run: |
          mkdir -p /github/home/.config/godot
          cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
      - name: Sanity check
        run: ls /root/.local/share/godot/export_templates
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
      - name: Initial Godot import
        shell: bash
        run: |
          godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
          godot --editor --headless --quit || exit 0
      - name: Web Build
        run: |
          mkdir -v -p dist/overculted-web
          godot --headless -v --export-debug overculted-web dist/overculted-web/index.html || exit 0
      - name: Sanity check
        run: |
          ls -alh dist/
          ls -alh dist/overculted-web
          stat dist/overculted-web/index.html
      - name: Deploy web build to itch.io (overculted)
        run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/overculted-web russmatney/overculted:html5

  # export-mac:
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   name: Mac Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.2.2
  #   environment: Godot Dev Env
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #     - name: Issue 120
  #       run: |
  #         mkdir -p /github/home/.config/godot
  #         cp /root/.config/godot/editor_settings-4.tres /github/home/.config/godot/
  #     - name: Sanity check
  #       run: ls /root/.local/share/godot/export_templates
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates
  #         mv /root/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ vars.GODOT_VERSION }}.stable
  #     - name: Initial Godot import
  #       shell: bash
  #       run: |
  #         godot --quiet --editor --headless -s addons/core/initial_import.gd || exit 0
  #         godot --editor --headless --quit || exit 0
  #     - name: Mac Build
  #       run: |
  #         mkdir -v -p dist/overculted-macos
  #         godot --headless -v --export-debug overculted-macos dist/overculted-macos/overculted.dmg || exit 0
  #     - name: Sanity check
  #       run: |
  #         ls -alh dist/
  #         ls -alh dist/overculted-macos
  #         stat dist/overculted-macos/overculted.dmg
  #     - name: Deploy mac build to itch.io
  #       run: BUTLER_API_KEY=${{secrets.BUTLER_API_KEY}} butler push dist/overculted-macos russmatney/overculted:macos
